[package]
name = "kvs"
version = "0.1.0"
authors = ["Kevin Teh <kevin@vinequai.com>"]
description = "A key-value store"
edition = "2021"

[dependencies]
clap = "2.34.0"
structopt = "0.3.25"


[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
